### ISSUE TITLE
Unable to run rpi_host.py

### ISSUE THREAD

**Issue by banchan86** [arnefmeyer/RPiCameraPlugin#3]
Hello Arne! I am setting up mousecam in my lab and was unable to run rpi_host.py in standalone mode (wanted to test it in standalone before doing the remote control via SSH)

My setup:
Installed Raspian buster on raspberry pi3 model B+
Installed Berryconda3-2.00 and created python 3.6 environment
installed picamera, pyzmq, RPi.GPIO and numpy
activated camera interface and SSH via sudo raspi-config
installed camera ardafruit 1937 on raspberry pi
tested the camera via "raspivid -o vid.h264" and can record video and see the camera preview

running the script in standalone mode throws me this error

```
(pupilcam) pi@raspberrypi:~/Desktop/rpicam/RPiCameraPlugin-master/Python/scripts $ python rpi_host.py standalone
Data path: RPiCamera_test
Opening controller and camera
Traceback (most recent call last):
  File "/home/pi/berryconda3/envs/pupilcam/lib/python3.6/site-packages/rpicamera/controller.py", line 146, in __init__
    self.camera = CameraGPIO(**kwargs)
  File "/home/pi/berryconda3/envs/pupilcam/lib/python3.6/site-packages/rpicamera/camera.py", line 112, in __init__
    for k, value in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Starting preview and warming up camera for 2 seconds
Starting recording
Traceback (most recent call last):
  File "rpi_host.py", line 289, in <module>
    out = func(**args)
  File "rpi_host.py", line 175, in run_standalone
    controller.resolution[0],
TypeError: 'NoneType' object is not subscriptable
/home/pi/berryconda3/envs/pupilcam/lib/python3.6/site-packages/rpicamera/camera.py:132: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()
(pupilcam) 
```
if i try it without standalone mode it gives me this error
```

pi@raspberrypi:~/Desktop/rpicam/RPiCameraPlugin-master/Python/scripts $ python rpi_host.py
Traceback (most recent call last):
  File "rpi_host.py", line 288, in <module>
    func = args.pop('func')
KeyError: 'func'
(pupilcam) pi@raspberrypi:~/Desktop/rpicam/RPiCameraPlugin-master/Python/scripts $ 

```

with the following messages:

**Comment by arnefmeyer** [comment]
Hey, it seems that there was some Python 2/3 incompatibility issue. I just committed a fix to the master branch.

**Comment by banchan86** [comment]
Thanks for the very quick fix! thought i replied it works now!
